const starterPlants = [
  { id: 1, commonName: 'Black-Eyed Susan', scientificName: 'Rudbeckia hirta', quantity: 2, bed: 'Garage Right', sun: 'Full Sun', moisture: 'Dry to Medium', native: true, notes: 'Small 2x2 accent bed.', bloomStart: 'June', bloomEnd: 'September', spread: 'Short-lived reseeder', aggression: 2, photo: '', printLabel: true },
  { id: 2, commonName: 'Gray Goldenrod', scientificName: 'Solidago nemoralis', quantity: 1, bed: 'Garage Left Rectangle', sun: 'Full Sun', moisture: 'Dry', native: true, notes: 'Moved to rectangle bed.', bloomStart: 'August', bloomEnd: 'October', spread: 'Clumping to moderate spread', aggression: 2, photo: '', printLabel: true },
  { id: 3, commonName: 'Butterfly Weed', scientificName: 'Asclepias tuberosa', quantity: 10, bed: 'Garage Left Rectangle', sun: 'Full Sun', moisture: 'Dry to Medium', native: true, notes: 'Tubers planned for planting.', bloomStart: 'June', bloomEnd: 'August', spread: 'Taproot, stays put', aggression: 1, photo: '', printLabel: true },
  { id: 4, commonName: 'Husker Red Beardtongue', scientificName: "Penstemon digitalis 'Husker Red'", quantity: 3, bed: 'Garage Left Peninsula', sun: 'Full Sun to Part Sun', moisture: 'Medium', native: true, notes: 'On peninsula with other established plants.', bloomStart: 'May', bloomEnd: 'June', spread: 'Clump-forming', aggression: 1, photo: '', printLabel: true },
  { id: 5, commonName: 'Rough Blazing Star', scientificName: 'Liatris aspera', quantity: 2, bed: 'Garage Left Peninsula', sun: 'Full Sun', moisture: 'Dry to Medium', native: true, notes: 'Sunny peninsula bed.', bloomStart: 'July', bloomEnd: 'September', spread: 'Slow clump', aggression: 1, photo: '', printLabel: true },
  { id: 6, commonName: 'Aromatic Aster', scientificName: 'Symphyotrichum oblongifolium', quantity: 1, bed: 'Garage Left Peninsula', sun: 'Full Sun', moisture: 'Dry to Medium', native: true, notes: 'Established on peninsula.', bloomStart: 'September', bloomEnd: 'October', spread: 'Steady clump spread', aggression: 2, photo: '', printLabel: true },
  { id: 7, commonName: "Summer Phlox 'Early Fuchsia'", scientificName: 'Phlox paniculata', quantity: 1, bed: 'Garage Left Peninsula', sun: 'Full Sun to Part Sun', moisture: 'Medium', native: false, notes: 'Peninsula planting.', bloomStart: 'June', bloomEnd: 'August', spread: 'Slow clump', aggression: 1, photo: '', printLabel: true },
  { id: 8, commonName: 'Peony', scientificName: 'Paeonia spp.', quantity: 2, bed: 'Back Porch Right', sun: 'Part Sun', moisture: 'Medium', native: false, notes: 'Two huge established plants anchoring the bed.', bloomStart: 'April', bloomEnd: 'May', spread: 'Non-spreading clump', aggression: 1, photo: '', printLabel: true },
  { id: 9, commonName: 'Jacob Cline Bee Balm', scientificName: "Monarda didyma 'Jacob Cline'", quantity: 3, bed: 'Back Porch Right', sun: 'Part Sun to Full Sun', moisture: 'Medium to Moist', native: true, notes: 'Around the peonies.', bloomStart: 'June', bloomEnd: 'August', spread: 'Rhizomes', aggression: 4, photo: '', printLabel: true },
  { id: 10, commonName: 'Virginia Mountain Mint', scientificName: 'Pycnanthemum virginianum', quantity: 1, bed: 'Back Porch Right', sun: 'Full Sun to Part Sun', moisture: 'Medium', native: true, notes: 'Very strong pollinator plant.', bloomStart: 'July', bloomEnd: 'September', spread: 'Rhizomes', aggression: 3, photo: '', printLabel: true },
  { id: 11, commonName: 'Wild Bergamot', scientificName: 'Monarda fistulosa', quantity: 1, bed: 'Back Porch Right', sun: 'Full Sun to Part Sun', moisture: 'Dry to Medium', native: true, notes: 'In peony bed.', bloomStart: 'June', bloomEnd: 'August', spread: 'Rhizomes and seed', aggression: 3, photo: '', printLabel: true },
  { id: 12, commonName: 'Obedient Plant', scientificName: 'Physostegia virginiana', quantity: 1, bed: 'Back Porch Right', sun: 'Full Sun to Part Sun', moisture: 'Medium to Moist', native: true, notes: 'Aggressive spreader. Watch it.', bloomStart: 'July', bloomEnd: 'September', spread: 'Fast rhizomes', aggression: 5, photo: '', printLabel: true },
  { id: 13, commonName: 'Coral Honeysuckle', scientificName: 'Lonicera sempervirens', quantity: 1, bed: 'Back Porch Right', sun: 'Full Sun to Part Shade', moisture: 'Medium', native: true, notes: 'Established vine.', bloomStart: 'April', bloomEnd: 'June', spread: 'Vine, manageable', aggression: 2, photo: '', printLabel: true },
  { id: 14, commonName: 'Jacob Cline Bee Balm', scientificName: "Monarda didyma 'Jacob Cline'", quantity: 2, bed: 'Back Porch Left', sun: 'Part Sun to Full Sun', moisture: 'Medium to Moist', native: true, notes: 'Back porch left group.', bloomStart: 'June', bloomEnd: 'August', spread: 'Rhizomes', aggression: 4, photo: '', printLabel: true },
  { id: 15, commonName: 'Blue Lobelia', scientificName: 'Lobelia siphilitica', quantity: 1, bed: 'Back Porch Left', sun: 'Part Sun', moisture: 'Medium to Moist', native: true, notes: 'Likes more moisture.', bloomStart: 'July', bloomEnd: 'September', spread: 'Clumping, some reseeding', aggression: 2, photo: '', printLabel: true },
  { id: 16, commonName: 'Western Sunflower', scientificName: 'Helianthus occidentalis', quantity: 2, bed: 'Front Right Meadow', sun: 'Full Sun', moisture: 'Dry to Medium', native: true, notes: 'Showpiece meadow bed.', bloomStart: 'July', bloomEnd: 'September', spread: 'Clump to patch over time', aggression: 2, photo: '', printLabel: true },
  { id: 17, commonName: 'Largeflower Aster', scientificName: 'Symphyotrichum grandiflorum', quantity: 2, bed: 'Front Right Meadow', sun: 'Full Sun', moisture: 'Dry', native: true, notes: 'Front right meadow.', bloomStart: 'September', bloomEnd: 'October', spread: 'Dry-site clump spread', aggression: 2, photo: '', printLabel: true },
  { id: 18, commonName: 'Snow Flurry Aster', scientificName: "Symphyotrichum ericoides 'Snow Flurry'", quantity: 3, bed: 'Front Right Meadow', sun: 'Full Sun', moisture: 'Dry to Medium', native: true, notes: 'Front right meadow.', bloomStart: 'September', bloomEnd: 'October', spread: 'Low spreading mound', aggression: 2, photo: '', printLabel: true },
  { id: 19, commonName: 'Fireworks Sundrops', scientificName: 'Oenothera lindheimeri', quantity: 3, bed: 'Front Right Meadow', sun: 'Full Sun', moisture: 'Dry to Medium', native: false, notes: 'Front right meadow.', bloomStart: 'May', bloomEnd: 'September', spread: 'Light airy clump', aggression: 1, photo: '', printLabel: true },
  { id: 20, commonName: 'Kobold Blazing Star', scientificName: "Liatris spicata 'Kobold'", quantity: 5, bed: 'Front Right Meadow', sun: 'Full Sun', moisture: 'Medium', native: true, notes: 'Front right meadow.', bloomStart: 'July', bloomEnd: 'August', spread: 'Slow clump', aggression: 1, photo: '', printLabel: true },
  { id: 21, commonName: 'Rattlesnake Master', scientificName: 'Eryngium yuccifolium', quantity: 1, bed: 'Front Right Meadow', sun: 'Full Sun', moisture: 'Dry to Medium', native: true, notes: 'Front right meadow.', bloomStart: 'June', bloomEnd: 'August', spread: 'Taproot, slow clump', aggression: 1, photo: '', printLabel: true },
  { id: 22, commonName: 'Wild Bergamot', scientificName: 'Monarda fistulosa', quantity: 1, bed: 'Front Right Meadow', sun: 'Full Sun', moisture: 'Dry to Medium', native: true, notes: 'Front right meadow.', bloomStart: 'June', bloomEnd: 'August', spread: 'Rhizomes and seed', aggression: 3, photo: '', printLabel: true },
  { id: 23, commonName: 'Garden Phlox', scientificName: 'Phlox paniculata', quantity: 1, bed: 'Front Right Meadow', sun: 'Full Sun to Part Sun', moisture: 'Medium', native: false, notes: 'Front right meadow.', bloomStart: 'June', bloomEnd: 'August', spread: 'Slow clump', aggression: 1, photo: '', printLabel: true },
  { id: 24, commonName: 'Coral Honeysuckle', scientificName: 'Lonicera sempervirens', quantity: 2, bed: 'Front Left Woodland', sun: 'Part Sun', moisture: 'Medium', native: true, notes: 'Front left vine layer.', bloomStart: 'April', bloomEnd: 'June', spread: 'Vine, manageable', aggression: 2, photo: '', printLabel: true },
  { id: 25, commonName: 'Southern Bush Honeysuckle', scientificName: 'Diervilla sessilifolia', quantity: 2, bed: 'Front Left Woodland', sun: 'Part Sun', moisture: 'Medium', native: true, notes: 'Moved to front left, beside each other.', bloomStart: 'June', bloomEnd: 'July', spread: 'Shrub, widening clump', aggression: 2, photo: '', printLabel: true },
  { id: 26, commonName: 'Celandine Poppy', scientificName: 'Stylophorum diphyllum', quantity: 1, bed: 'Front Left Woodland', sun: 'Part Shade', moisture: 'Medium', native: true, notes: 'May fade in summer heat.', bloomStart: 'March', bloomEnd: 'May', spread: 'Reseeding woodland perennial', aggression: 2, photo: '', printLabel: true },
  { id: 27, commonName: 'Fameflower', scientificName: 'Phemeranthus calycinus', quantity: 1, bed: 'Front Left Woodland', sun: 'Full Sun to Part Sun', moisture: 'Dry', native: true, notes: 'Front left placement.', bloomStart: 'June', bloomEnd: 'September', spread: 'Small clump', aggression: 1, photo: '', printLabel: true },
  { id: 28, commonName: 'Black-Eyed Susan', scientificName: 'Rudbeckia hirta', quantity: 2, bed: 'Front Left Woodland', sun: 'Full Sun to Part Sun', moisture: 'Dry to Medium', native: true, notes: 'Two in front left.', bloomStart: 'June', bloomEnd: 'September', spread: 'Short-lived reseeder', aggression: 2, photo: '', printLabel: true },
  { id: 29, commonName: 'Wild Red Columbine', scientificName: 'Aquilegia canadensis', quantity: 1, bed: 'Front Left Woodland', sun: 'Part Shade', moisture: 'Medium', native: true, notes: 'Woodland transition plant.', bloomStart: 'April', bloomEnd: 'May', spread: 'Gentle reseeder', aggression: 1, photo: '', printLabel: true },
  { id: 30, commonName: 'Blue Moon Woodland Phlox', scientificName: 'Phlox divaricata', quantity: 1, bed: 'Front Left Woodland', sun: 'Part Shade', moisture: 'Medium', native: true, notes: 'Woodland transition plant.', bloomStart: 'March', bloomEnd: 'May', spread: 'Slow mat-forming', aggression: 1, photo: '', printLabel: true }
];
const bedOptions = ['Garage Right','Garage Left Rectangle','Garage Left Peninsula','Back Porch Right','Back Porch Left','Front Right Meadow','Front Left Woodland','Other'];
const bedMapNotes = {
  'Garage Right': 'Small 2x2 accent bed.',
  'Garage Left Rectangle': 'Main open bed with goldenrod and butterfly weed planting zone.',
  'Garage Left Peninsula': 'Established peninsula with beardtongue, blazing star, aster, and phlox.',
  'Back Porch Right': 'Peony-centered pollinator bed with aggressive spreaders.',
  'Back Porch Left': 'Smaller moist-leaning bed with bee balm and blue lobelia.',
  'Front Right Meadow': 'Showpiece meadow bed, already full.',
  'Front Left Woodland': 'Woodland-transition zone with shrubs, vines, and shade-tolerant plants.'
};
let plants = structuredClone(starterPlants);
let currentTab = 'plants';
let pendingPhoto = '';
const $ = (id) => document.getElementById(id);
function aggressionLabel(v){ return v<=1?'Low':v===2?'Mild':v===3?'Moderate':v===4?'High':'Very High'; }
function exportJson(){ const blob=new Blob([JSON.stringify(plants,null,2)],{type:'application/json'}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download='native-garden-plants.json'; a.click(); URL.revokeObjectURL(url); }
function printableText(){ return plants.filter(p=>p.printLabel).map(p=>`${p.commonName}\n${p.scientificName}\n${p.bed}`).join('\n\n-------------------------\n\n'); }
function groupedByBed(list){ return list.reduce((acc,p)=>{ (acc[p.bed] ||= []).push(p); return acc; },{}); }
function filteredPlants(){ const q=$('searchInput').value.toLowerCase(); const bed=$('bedFilter').value; const nativeOnly=$('nativeOnly').checked; return plants.filter(p=>{ const hay=[p.commonName,p.scientificName,p.notes,p.bed,p.bloomStart,p.bloomEnd,p.spread].join(' ').toLowerCase(); return hay.includes(q) && (bed==='All Beds'||p.bed===bed) && (!nativeOnly || p.native); }); }
function renderStats(){ $('statPlants').textContent = plants.reduce((s,p)=>s+Number(p.quantity||0),0); $('statBeds').textContent = new Set(plants.map(p=>p.bed)).size; $('statNative').textContent = plants.filter(p=>p.native).length; }
function renderPlants(){ const grid=$('plantsGrid'); grid.innerHTML=''; filteredPlants().forEach(p=>{ const card=document.createElement('article'); card.className='card'; card.innerHTML=`<div class="card-header-row"><div><h3>${p.commonName}</h3><div class="sci-name">${p.scientificName}</div></div><button class="icon-button no-print" data-delete="${p.id}">×</button></div><div class="badges"><span class="badge">Qty: ${p.quantity}</span><span class="badge outline">${p.bed}</span><span class="${p.native?'badge native':'badge'}">${p.native?'Native':'Non-native'}</span><span class="badge">Spread: ${aggressionLabel(p.aggression)}</span></div>${p.photo?`<img src="${p.photo}" alt="${p.commonName}" class="plant-photo" />`:''}<div class="meta"><strong>Sun:</strong> ${p.sun||'—'}</div><div class="meta"><strong>Moisture:</strong> ${p.moisture||'—'}</div><div class="meta"><strong>Bloom:</strong> ${p.bloomStart||'—'} ${p.bloomEnd?`to ${p.bloomEnd}`:''}</div><div class="meta"><strong>Spread habit:</strong> ${p.spread||'—'}</div><div class="meta"><strong>Notes:</strong> ${p.notes||'—'}</div><label class="checkbox-row no-print"><input type="checkbox" data-label="${p.id}" ${p.printLabel?'checked':''}/> Include in printable labels</label>`; grid.appendChild(card); });
  grid.querySelectorAll('[data-delete]').forEach(btn=>btn.onclick=()=>{ plants=plants.filter(p=>p.id!==Number(btn.dataset.delete)); renderAll(); });
  grid.querySelectorAll('[data-label]').forEach(cb=>cb.onchange=()=>{ const id=Number(cb.dataset.label); plants=plants.map(p=>p.id===id?{...p,printLabel:cb.checked}:p); renderAll(); });
}
function renderBeds(){ const stack=$('bedsStack'); stack.innerHTML=''; Object.entries(groupedByBed(filteredPlants())).forEach(([bed,bedPlants])=>{ const card=document.createElement('article'); card.className='card'; card.innerHTML=`<h2>${bed}</h2><p class="subtle">${bedMapNotes[bed]||''}</p><div class="cards-grid"></div>`; const inner=card.querySelector('.cards-grid'); bedPlants.forEach(p=>{ const d=document.createElement('div'); d.className='mini-card'; d.innerHTML=`<div class="mini-title">${p.commonName}</div><div class="sci-name">${p.scientificName}</div><div class="meta">Quantity: ${p.quantity}</div><div class="meta">Bloom: ${p.bloomStart} to ${p.bloomEnd}</div><div class="meta">Spread: ${p.spread}</div>`; inner.appendChild(d); }); stack.appendChild(card); }); }
function renderBloom(){ const stack=$('bloomStack'); stack.innerHTML=''; const list=[...plants].filter(p=>p.bloomStart&&p.bloomEnd).sort((a,b)=>a.bloomStart.localeCompare(b.bloomStart)); const card=document.createElement('article'); card.className='card'; card.innerHTML='<h2>Bloom and Spread Guide</h2><div class="stack" id="bloomInner"></div>'; const inner=card.querySelector('#bloomInner'); list.forEach(p=>{ const d=document.createElement('div'); d.className='mini-card'; d.innerHTML=`<div class="card-header-row"><div><div class="mini-title">${p.commonName}</div><div class="sci-name">${p.scientificName}</div></div><div class="badges"><span class="badge outline">${p.bed}</span><span class="badge">${p.bloomStart} to ${p.bloomEnd}</span><span class="badge">Aggression: ${aggressionLabel(p.aggression)}</span></div></div><div class="meta">Spread habit: ${p.spread}</div>`; inner.appendChild(d); }); stack.appendChild(card); }
function renderLabels(){ $('labelsBlock').textContent = printableText() || 'No labels selected yet.'; }
function renderBedNotes(){ const notes=$('bedNotes'); notes.innerHTML=''; Object.entries(bedMapNotes).forEach(([bed,note])=>{ const d=document.createElement('div'); d.className='map-bed'; d.innerHTML=`<strong>${bed}</strong><br>${note}`; notes.appendChild(d); }); }
function renderAll(){ renderStats(); renderPlants(); renderBeds(); renderBloom(); renderLabels(); renderBedNotes(); }
function initSelects(){ const opts=['All Beds',...bedOptions]; $('bedFilter').innerHTML = opts.map(o=>`<option>${o}</option>`).join(''); $('formBed').innerHTML = bedOptions.map(o=>`<option>${o}</option>`).join(''); }
function initTabs(){ document.querySelectorAll('.tab').forEach(btn=>btn.onclick=()=>{ currentTab=btn.dataset.tab; document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b===btn)); document.querySelectorAll('.tab-panel').forEach(p=>p.classList.toggle('active',p.id===`tab-${currentTab}`)); }); }
function initEvents(){ $('searchInput').oninput=renderAll; $('bedFilter').onchange=renderAll; $('nativeOnly').onchange=renderAll; $('exportBtn').onclick=exportJson; $('printBtn').onclick=()=>window.print(); $('importInput').onchange=(e)=>{ const file=e.target.files[0]; if(!file) return; const reader=new FileReader(); reader.onload=()=>{ try{ const parsed=JSON.parse(reader.result); if(Array.isArray(parsed)){ plants=parsed; renderAll(); } }catch(err){ alert('Invalid JSON file.'); } }; reader.readAsText(file); };
  $('photoInput').onchange=(e)=>{ const file=e.target.files[0]; if(!file) return; const reader=new FileReader(); reader.onload=()=>{ pendingPhoto=String(reader.result); $('photoPreview').src=pendingPhoto; $('photoPreview').hidden=false; }; reader.readAsDataURL(file); };
  $('addForm').onsubmit=(e)=>{ e.preventDefault(); const fd=new FormData(e.target); plants.unshift({ id:Date.now(), commonName:fd.get('commonName'), scientificName:fd.get('scientificName'), quantity:Number(fd.get('quantity')||1), bed:fd.get('bed'), sun:fd.get('sun'), moisture:fd.get('moisture'), native:fd.get('native')==='on', notes:fd.get('notes'), bloomStart:fd.get('bloomStart'), bloomEnd:fd.get('bloomEnd'), spread:fd.get('spread'), aggression:Number(fd.get('aggression')||1), photo:pendingPhoto, printLabel:fd.get('printLabel')==='on' }); e.target.reset(); pendingPhoto=''; $('photoPreview').hidden=true; document.querySelector('[data-tab="plants"]').click(); renderAll(); };
}
initSelects(); initTabs(); initEvents(); renderAll();
